services:
  database:
    image: postgis/postgis:17-3.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DEV_DB_PASS}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-cache
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-seeds:
    image: redis/redis-stack-server:latest
    container_name: redis-seeder
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./redis-seed.txt:/data/seed.txt
    command: >
      sh -c "cat /data/seed.txt | redis-cli -h redis --pipe"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      REDIS_HOST: redis
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DEV_DB_USER}
      DB_PASS: ${DEV_DB_PASS}
      DB_NAME: ${DEV_DB_NAME}
      PORT: 3000
      NODE_ENV: development
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    command: ["sh", "/usr/local/bin/docker-entrypoint.sh"]
