openapi: 3.0.0
info:
  title: Natural Disaster Relief System API
  version: 1.0.0
  description: API documentation for Natural Disaster Relief System
servers:
  - url: http://localhost:3000

paths:
  /user:
    get:
      summary: Get User profile
      operationId: User_getUser
      responses:
        201:
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: User profile edit
      operationId: User_editUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        200:
          description: User profile edit successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete User
      operationId: User_deleteUser
      security:
        - bearerAuth: []
      responses:
        200:
          description: User profile deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/register:
    post:
      summary: Register a new user
      operationId: User_registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        201:
          description: User signed in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthentication'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/auth:
    post:
      summary: User login
      operationId: User_signInUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignIn'
      responses:
        201:
          description: User signed in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthentication'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /categories:
    get:
      summary: Get all categories
      operationId: Category_getAll
      responses:
        200:
          description: Get all categories successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /units:
    get:
      summary: Get all units
      operationId: Unit_getAll
      responses:
        200:
          description: Get all units successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnitsResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supplies:
    get:
      summary: Get all verified supply offers
      operationId: SupplyGetAllVerified_getAll
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: The number of items to return
          required: false
          schema:
            type: integer
            default: 100
      responses:
        200:
          description: Get all verified supply offers successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supplies/unverified:
    get:
      summary: Get all unverified supply offers
      operationId: SupplyGetAllUnverified_getAll
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: The number of items to return
          required: false
          schema:
            type: integer
            default: 100
      responses:
        200:
          description: Get all unverified supply offers successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supplies/me:
    get:
      summary: Get all current user's verified supply offers
      operationId: SupplyGetMineVerified_getMine
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: The number of items to return
          required: false
          schema:
            type: integer
            default: 100
      responses:
        200:
          description: Get all current user's verified supply offers successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supplies/me/unverified:
    get:
      summary: Get all current user's unverified supply offers
      operationId: SupplyGetMineUnverified_getMine
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: The number of items to return
          required: false
          schema:
            type: integer
            default: 100
      responses:
        200:
          description: Get all current user's unverified supply offers successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supply/unverified/{id}:
    get:
      summary: Get an unverified supply offer
      operationId: SupplyGetOneUnverified_getOne
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      responses:
        200:
          description: Get an unverified supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supply:
    post:
      summary: Create a new supply offer
      operationId: SupplyCreateService_create
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyRequest'
      responses:
        201:
          description: Create a new supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supply/{id}:
    get:
      summary: Get a verified supply offer
      operationId: SupplyGetOneVerified_getOne
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      responses:
        200:
          description: Get a verified supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Accept an unverified supply
      operationId: SupplyCreateAcceptService_create
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      responses:
        201:
          description: Accept an unverified supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Donor edit an unverified supply offer
      operationId: Supply_edit
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyRequest'
      responses:
        201:
          description: Edit a supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Donor delete an unverified supply offer
      operationId: Supply_delete
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      responses:
        200:
          description: Delete a supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /supply/{id}/review:
    get:
      summary: Get a review on a supply offer
      operationId: Supply_getReview
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      responses:
        200:
          description: Get a review on a supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyReviewResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a review for a supply offer
      operationId: Supply_review
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyRequest'
      responses:
        201:
          description: Create a review for a supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyReviewResponse'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /supply/{id}/proof:
    post:
      summary: Add a photo url to a supply offer
      operationId: Supply_addProof
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of supply offer
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proof'
      responses:
        201:
          description: Add a photo url to a supply offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        500:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        email: { type: string }
        name: { type: string }
        username: { type: string }
        phone: { type: string }
        address_line: { type: string }
        ward: { type: string }
        district: { type: string }
        city_province: { type: string }

    UserRequest:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            password: { type: string }
            role: { type: string }

    UserResponse:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            role: { type: string }

    UserProfile:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            password: { type: string }

    UserAuthentication:
      type: object
      properties:
        message: { type: string }
        token: { type: string }

    UserSignIn:
      type: object
      properties:
        username: { type: string }
        password: { type: string }

    Categories:
      type: object
      description: "A map of category IDs to unit names"
      additionalProperties:
        type: string
      example:
        "1": "thuốc"
        "2": "thực phẩm"
        "3": "nước"
        "4": "vật dụng"
        "5": "tiền"

    CategoriesResponse:
      type: object
      properties:
        message: { type: string }
        categories:
          $ref: '#/components/schemas/Categories'
    
    Units:
      type: object
      description: "A map of unit IDs to unit names"
      additionalProperties:
        type: string
      example:
        "1": "kg"
        "2": "l"
        "3": "phần"
        "4": "cái"
        "5": "nghìn VND"
    
    UnitsResponse:
      type: object
      properties:
        message: { type: string }
        units:
          $ref: '#/components/schemas/Units'

    SupplyRequest:
      allOf:
        - $ref: '#/components/schemas/BaseSupply'
        - type: object
          properties:
            category:
              type: integer
            unit:
              type: integer

    BaseSupply:
      type: object
      properties:
        name: { type: string }
        count: { type: integer }
        quantity:
          type: number
          format: float
          example: 19.99
        address_line: { type: string }
        ward: { type: string }
        district: { type: string }
        city_province: { type: string }

    Supply:
      allOf:
        - $ref: '#/components/schemas/BaseSupply'
        - type: object
          properties:
            id: { type: integer }
            category: { type: string }
            unit: { type: string }
            donor: { type: string }
            createdAt:
              type: string
              format: date-time
              example: "2025-12-28T21:23:27Z"
            updatedAt:
              type: string
              format: date-time
              example: "2025-12-28T21:23:27Z"

    SuppliesResponse:
      type: object
      properties:
        message: { type: string }
        supplies:
          type: array
          items:
            $ref: '#/components/schemas/Supply'
        total_records: { type: integer }

    SupplyResponse:
      type: object
      properties:
        message: { type: string }
        supply:
          $ref: '#/components/schemas/Supply'

    SupplyReview:
      allOf:
        - $ref: '#/components/schemas/BaseSupply'
        - type: object
          properties:
            id: { type: integer }
            category: { type: string }
            unit: { type: string }
            donor: { type: string }
            reviewer: { type: string }
            updated:
              type: boolean
            createdAt:
              type: string
              format: date-time
              example: "2025-12-28T21:23:27Z"

    SupplyReviewResponse:
      type: object
      properties:
        message: { type: string }
        review:
          $ref: '#/components/schemas/SupplyReview'

    Success:
      type: object
      properties:
        message: { type: string }

    Proof:
      type: object
      properties:
        proof: { type: string }

    Error:
      type: object
      properties:
        message: { type: string }